version: '2'

services:

  desi-cloud:
    build: ./desi-cloud
    ports:
      - 8080:80
    restart: always

  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: '1'

  desi-api:
    build: ./desi-api
    ports:
      - 8080:80
    restart: always
